core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

django_course/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),
    # this is our new URL config
    path('', include('users.urls', namespace="users")),
    path("__debug__/", include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('sign-up/', views.SignUpView.as_view(), name="sign-up"),
    path('sign-in/', views.SignInView.as_view(), name="sign-in"),
    path('sign-out/', views.sign_out, name="sign-out"),
    # We have removed '.as_view()',
    path('account/', views.AccountView, name="account"),
    # We have removed '.as_view()'
    path('user-info/', views.UserInfoView, name="user-info"),
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
import pycountry
from operator import itemgetter

# these are model abstracts from django extensions
from django_extensions.db.models import (
    TimeStampedModel,
    ActivatorModel
)

country_list = sorted(
    [(country.name, country.name)
     for country in list(pycountry.countries)], key=itemgetter(0))

country_list.insert(0, ("*Select Country", "*Select Country"))

# (('United Kingdom', 'United Kingdom'), ('France', 'France').....)
COUNTRIES = country_list


class UserProfile(TimeStampedModel, ActivatorModel, models.Model):
    '''
    users.UserProfile
    Stores a single user profile entry related to :model:`auth.User`
    '''
    class Meta:
        verbose_name_plural = 'User profiles'
        ordering = ["id"]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telephone = models.CharField(
        verbose_name="Contact telephone number", max_length=255, null=True, blank=True)
    address = models.CharField(
        verbose_name="Address", max_length=100, null=True, blank=True)
    town = models.CharField(verbose_name="Town/City",
                            max_length=100, null=True, blank=True)
    county = models.CharField(verbose_name="County",
                              max_length=100, null=True, blank=True)
    post_code = models.CharField(
        verbose_name="Zip/Post Code", max_length=8, null=True, blank=True)
    country = models.CharField(
        verbose_name="Country", max_length=100, null=True, blank=True, choices=COUNTRIES)

    longitude = models.CharField(
        verbose_name="Longitude", max_length=50, null=True, blank=True)
    latitude = models.CharField(
        verbose_name="Latitude", max_length=50, null=True, blank=True)

    avatar = models.ImageField(default='default_avatar.jpg', upload_to='avatar',
                               null=True, blank=True)  # this is our new avatar filed

    @property
    def country_alpha_2(self):
        '''
        Used to return the selected countries alpha 2 repr i.e. England == GB
        '''
        if self.country:
            return pycountry.countries.get(name=self.country).alpha_2
        else:
            return None

    def full_name(self):
        '''
        Return full name or email
        '''
        if self.user.first_name and self.user.last_name:
            return f'{self.user.first_name.capitalize()} {self.user.last_name.capitalize()}'
        if self.user.email:
            return self.user.email
        return self.user.email

    def __str__(self):
        return self.full_name()

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile, COUNTRIES


class UserForm(UserCreationForm):
    '''
    Form that uses built-in UserCreationForm to handel user creation
    '''
    username = forms.CharField(
        max_length=150, required=True, widget=forms.TextInput())
    password1 = forms.CharField(required=True, widget=forms.PasswordInput())
    password2 = forms.CharField(required=True, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class AuthForm(AuthenticationForm):
    '''
    Form that uses built-in AuthenticationForm to handel user auth
    '''
    username = forms.CharField(
        max_length=150, required=True, widget=forms.TextInput())
    password = forms.CharField(required=True, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class UserProfileForm(forms.ModelForm):
    '''
    Basic model-form for our user profile
    '''
    avatar = forms.ImageField(required=False)
    telephone = forms.CharField(
        max_length=255, required=False, widget=forms.TextInput())
    address = forms.CharField(
        max_length=100, required=False, widget=forms.TextInput())
    town = forms.CharField(max_length=100, required=False,
                           widget=forms.TextInput())
    county = forms.CharField(
        max_length=100, required=False, widget=forms.TextInput())
    post_code = forms.CharField(
        max_length=8, required=False, widget=forms.TextInput())
    country = forms.CharField(
        max_length=100, required=False, widget=forms.Select(choices=COUNTRIES))

    class Meta:
        model = UserProfile
        fields = ('avatar', 'telephone', 'address',
                  'town', 'county', 'post_code', 'country')


class UserAlterationForm(forms.ModelForm):
    '''
    Basic model-form for our user
    '''
    first_name = forms.CharField(
        max_length=150, required=True, widget=forms.TextInput())
    last_name = forms.CharField(
        max_length=150, required=True, widget=forms.TextInput())
    email = forms.EmailField(
        max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

users/views.py
from django.views import generic
from django.shortcuts import redirect, reverse, render
from django.contrib.auth import logout, login
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .forms import UserForm, AuthForm, UserProfileForm, UserAlterationForm
from .models import UserProfile


class SignUpView(generic.FormView):
    """
    Basic user sign up page.

    **Template:**

    :template:`users/sign_up.html`
    """
    template_name = "users/sign_up.html"
    form_class = UserForm
    success_url = '/account/'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return HttpResponseRedirect(self.get_success_url())


class SignInView(generic.FormView):
    """
    Basic user sign up page.

    **Template:**

    :template:`users/sign_in.html`
    """
    template_name = "users/sign_in.html"
    form_class = AuthForm
    success_url = '/account/'

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())


def sign_out(request):
    """
Basic user sign out page.
"""
    logout(request)
    return redirect(reverse('users:sign-in'))


@login_required
def AccountView(request):
    """
    User account page. CRUD account details.

    **Template:**

    :template:`users/account.html`
    """
    up = request.user.userprofile
    up_form = UserProfileForm(instance=up)
    context = {'form': up_form}

    if request.method == "POST":
        form = UserProfileForm(
            instance=up, data=request.POST, files=request.FILES)
        if form.is_valid:
            form.save()
            return redirect('/account/')
    else:
        return render(request, 'users/account.html', context)


@login_required
def UserInfoView(request):
    """
    User information page. CRUD profile details.

    **Template:**

    :template:`users/info.html`
    """
    user = request.user
    u_form = UserAlterationForm(instance=user)
    context = {'form': u_form}

    if request.method == "POST":
        form = UserAlterationForm(instance=user, data=request.POST)
        if form.is_valid:
            form.save()
            return redirect('/user-info/')
    else:
        return render(request, 'users/info.html', context)

templates/users/account.html
{% extends 'base/base.html' %} {% block extend_head %}
<link
  href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.2.5/css/fileinput.min.css"
  media="all"
  rel="stylesheet"
  type="text/css"
/>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.min.css"
  crossorigin="anonymous"
/>
<style>
  .kv-avatar .krajee-default.file-preview-frame,
  .kv-avatar .krajee-default.file-preview-frame:hover {
    margin: 0;
    padding: 0;
    border: none;
    box-shadow: none;
    text-align: center;
  }
  .kv-avatar {
    display: inline-block;
    max-width: 100%;
  }
  .kv-avatar .file-input {
    display: table-cell;
  }
  .file-default-preview > img:nth-child(1) {
    max-width: 100% !important;
  }
  .kv-avatar .file-default-preview .img {
    max-width: 100% !important;
  }
  .kv-reqd {
    color: red;
    font-family: monospace;
    font-weight: normal;
  }
</style>
{% endblock %} {% block extend_foot %}
<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.2.5/js/fileinput.min.js"></script>
<script>
  var avatar_url = "{{request.user.userprofile.avatar.url|safe}}";
  var btnCust =
    '<button type="button" class="btn btn-secondary" title="Add picture tags" ' +
    "onclick=\"alert('Call your custom code here.')\">" +
    '<i class="bi-tag"></i>' +
    "</button>";
  $("#id_avatar").fileinput({
    overwriteInitial: true,
    maxFileSize: 1500,
    showClose: false,
    showCaption: false,
    browseLabel: "",
    removeLabel: "",
    browseIcon: '<i class="bi-folder2-open"></i>',
    removeIcon: '<i class="bi-x-lg"></i>',
    removeTitle: "Cancel or reset changes",
    elErrorContainer: "#kv-avatar-errors-1",
    msgErrorClass: "alert alert-block alert-danger",
    defaultPreviewContent: '<img src="' + avatar_url + '" alt="Your Avatar">',
    layoutTemplates: { main2: "{preview} {remove} {browse}" },
    allowedFileExtensions: ["jpg", "png", "gif"],
  });
</script>
{% endblock %} {% block content %}
<h1>Welcome to your account {{request.user.userprofile.full_name}}</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="col-sm-4 text-center">
    <div class="kv-avatar">
      <div class="file-loading">
        <input id="id_avatar" name="avatar" type="file" />
      </div>
    </div>
    <div class="kv-avatar-hint">
      <small>Select file < 1500 KB</small>
    </div>
  </div>
  <p><label>Telephone:</label>{{form.telephone}}</p>
  <p><label>Address:</label>{{form.address}}</p>
  <p><label>Town:</label>{{form.town}}</p>
  <p><label>County:</label>{{form.county}}</p>
  <p><label>Post Code:</label>{{form.post_code}}</p>
  <p><label>Country:</label>{{form.country}}</p>
  <button type="submit">Submit!</button>
</form>
<div id="kv-avatar-errors-1" class="text-center" style="display: none"></div>
{% endblock %}

templates/users/info.html
{% extends 'base/base.html' %} {% block content %}
<h1>Info - {{request.user.userprofile.full_name}}</h1>
<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <button type="submit">Submit!</button>
</form>
{% endblock %}

templates/users/sign_in.html
{% extends 'base/base.html' %} {% block content %}
<h1>Sign in</h1>
<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <button type="submit">Submit!</button>
</form>
<br />
<a href="{% url 'users:sign-up' %}">Sign up</a>
{% endblock %}

templates/users/sign_up.html
{% extends 'base/base.html' %} {% block content %}
<h1>Sign up</h1>
<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <button type="submit">Submit!</button>
</form>
<br />
<a href="{% url 'users:sign-in' %}">Sign in</a>
{% endblock %}